apiVersion: v1
kind: Service
metadata:
  name: static
  annotations:
    # select from the layer3 bgp ip address pool
    metallb.universe.tf/address-pool: lab-192-168-179-224-b29
spec:
  type: LoadBalancer
