apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  name: l2advertisement
#spec: {} # all ipaddresspools
spec:
  ipAddressPools:
    - lab-192-168-4-224-b29
