apiVersion: v1
kind: Service
metadata:
  name: static
  annotations:
    # select from the layer2 ip address pool
    metallb.universe.tf/address-pool: lab-192-168-4-224-b29
spec:
  type: LoadBalancer
