apiVersion: v1
kind: Namespace
metadata:
  name: metallb
---
apiVersion: metallb.io/v1alpha1
kind: AddressPool
metadata:
  name: addresspool
  namespace: metallb
spec:
  addresses:
  - 192.168.4.224-192.168.4.231
  protocol: layer2
---
apiVersion: metallb.io/v1beta1
kind: MetalLB
metadata:
  name: metallb
  namespace: metallb
spec:
  nodeSelector:
    node-role.kubernetes.io/worker: ""
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  annotations:
    olm.providedAPIs: AddressPool.v1alpha1.metallb.io,MetalLB.v1beta1.metallb.io
  generateName: metallb-
  generation: 1
  name: metallb
  namespace: metallb
spec:
  targetNamespaces:
  - metallb
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  labels:
    operators.coreos.com/metallb-operator.metallb: ""
  name: metallb
  namespace: metallb
spec:
  channel: stable
  installPlanApproval: Automatic
  name: metallb-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
