# ---
# apiVersion: metallb.io/v1beta1
# kind: BGPPeer
# metadata:
#  namespace: metallb-system
#  name: vrf_oam
# spec:
#  peerAddress: 172.16.10.1
#  peerASN: 6666
#  password: “MD5 Password”
#  myASN: 9999
#  routerID: 10.254.0.1
#  bfdProfile: bfd-fastest

---
apiVersion: metallb.io/v1beta1
kind: BGPPeer
metadata:
  name: peer-test
spec:
  bfdProfile: test-bfd-prof
  myASN: 64520
  peerASN: 64521
  # peerAddress: 192.168.133.1
  peerAddress: 192.168.4.2

  nodeSelectors:
    - matchLabels:
        machine.openshift.io/cluster-api-machineset: hub-q4jtr-cnv